name: native_i18n_flutter_plugin
description: Internationalization plugin based on Native APIs
version: 0.0.1
author: Victor Escobar <victorescobargonza@gmail.com>
homepage: https://github.com/vistiyos/native_i18n_flutter_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.6.0
  args: ^1.5.2
  xml: ^3.5.0
  build: ^1.1.4
  build_config: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^0.37.0

flutter:
  plugin:
    androidPackage: com.github.vistiyos.native_i18n_flutter_plugin
    pluginClass: NativeI18nFlutterPlugin

executables:
  i18_gen: i18_gen
